<!-- Kopioi tämä teksti tehtävänantoon. Itse aukkoteksti laitetaan tehtävänantoon normaalisti, aukon kohdalle kirjoitetaan [] -->

<script sec="apuri" type="application/javascript" id="apuri_script">

// Input 0

if("undefined"===typeof APURI)var APURI={};"function"!==typeof APURI.paivvast&&(APURI.paivvast=function(a,b,c,k,l){c=$("#"+c);var d=c.val().split("\n");d[k-1]="#"+k+":"+b.value;c.val(d.join("\n"));1==l&&9!=a.keyCode&&(b=jQuery.Event("keydown"),b.which=a.which,c.trigger(b),b=jQuery.Event("keyup"),b.which=a.which,c.trigger(b))});"undefined"===typeof APURI.kentta&&(APURI.kentta=[]);

"function"!==typeof APURI.purku&&(APURI.purku=function(a){"undefined"===typeof APURI.kentta[APURI.count]&&(APURI.kentta[APURI.count]=0);var b;b=document.createElement(a.tagName);for(var c in a.attributes)b.setAttribute(c.name,a.attributes[c].value);a.hasChildNodes()&&a.childNodes.forEach(function(a,c){if(a.nodeType==Node.TEXT_NODE){for(var d=a.textContent.trim().split("[]"),g=document.createElement("span"),f=0;f<d.length;f++){if(0<f){APURI.kentta[APURI.count]++;var h=document.createElement("form");

h.style.display="inline";var e=document.createElement("input");e.setAttribute("type","text");e.setAttribute("length","10");e.setAttribute("onChange","APURI.paivvast(event, this, 'apuri_vastk_"+APURI.count+"', "+APURI.kentta[APURI.count]+", false);");e.setAttribute("onKeyup","APURI.paivvast(event, this, 'apuri_vastk_"+APURI.count+"', "+APURI.kentta[APURI.count]+", true);");h.appendChild(e);g.appendChild(h)}g.appendChild(document.createTextNode(d[f]))}b.appendChild(g)}else a.nodeType==Node.ELEMENT_NODE&&

"SCRIPT"!=a.tagName&&(a.textContent.includes("[]")?b.appendChild(APURI.purku(a)):b.appendChild(a.cloneNode(!0)))});return b});"undefined"===typeof APURI.count?APURI.count=1:APURI.count++;"undefined"===typeof APURI.pjono&&(APURI.pjono=[]);

(function(){var a;(a=document.currentScript)||(a=document.getElementsByTagName("script"),a=a[a.length-1]);"BODY"==a.parentNode.tagName&&(a=document.getElementById("apuri_script"));for(a=a.parentNode;"SPAN"!==a.tagName.toUpperCase()&&"text"!==a.className.toLowerCase;)a=a.parentNode;APURI.pjono[APURI.count]=a;a.style.display="none";var b=a.parentNode,c=a.parentNode.parentNode.querySelector("textarea.answerText");c.id="apuri_vastk_"+APURI.count;c.style.height="10px";c.style.display="none";c=APURI.purku(a);

b.insertBefore(c,a.nextSibling)})();

</script>
"<script sec=\"apuri\" type=\"application/javascript\" id=\"apuri_script\">if(\"undefined\"===typeof APURI)var APURI={};\"function\"!==typeof APURI.paivvast&&(APURI.paivvast=function(a,b,c,k,l){c=$(\"#\"+c);var d=c.val().split(\"\n\");d[k-1]=\"#\"+k+\":\"+b.value;c.val(d.join(\"\n\"));1==l&&9!=a.keyCode&&(b=jQuery.Event(\"keydown\"),b.which=a.which,c.trigger(b),b=jQuery.Event(\"keyup\"),b.which=a.which,c.trigger(b))});\"undefined\"===typeof APURI.kentta&&(APURI.kentta=[]);\"function\"!==typeof APURI.purku&&(APURI.purku=function(a){\"undefined\"===typeof APURI.kentta[APURI.count]&&(APURI.kentta[APURI.count]=0);var b;b=document.createElement(a.tagName);for(var c in a.attributes)b.setAttribute(c.name,a.attributes[c].value);a.hasChildNodes()&&a.childNodes.forEach(function(a,c){if(a.nodeType==Node.TEXT_NODE){for(var d=a.textContent.trim().split(\"[]\"),g=document.createElement(\"span\"),f=0;f<d.length;f++){if(0<f){APURI.kentta[APURI.count]++;var h=document.createElement(\"form\");h.style.display=\"inline\";var e=document.createElement(\"input\");e.setAttribute(\"type\",\"text\");e.setAttribute(\"length\",\"10\");e.setAttribute(\"onChange\",\"APURI.paivvast(event, this, 'apuri_vastk_\"+APURI.count+\"', \"+APURI.kentta[APURI.count]+\", false);\");e.setAttribute(\"onKeyup\",\"APURI.paivvast(event, this, 'apuri_vastk_\"+APURI.count+\"', \"+APURI.kentta[APURI.count]+\", true);\");h.appendChild(e);g.appendChild(h)}g.appendChild(document.createTextNode(d[f]))}b.appendChild(g)}else a.nodeType==Node.ELEMENT_NODE&&\"SCRIPT\"!=a.tagName&&(a.textContent.includes(\"[]\")?b.appendChild(APURI.purku(a)):b.appendChild(a.cloneNode(!0)))});return b});\"undefined\"===typeof APURI.count?APURI.count=1:APURI.count++;\"undefined\"===typeof APURI.pjono&&(APURI.pjono=[]);(function(){var a;(a=document.currentScript)||(a=document.getElementsByTagName(\"script\"),a=a[a.length-1]);\"BODY\"==a.parentNode.tagName&&(a=document.getElementById(\"apuri_script\"));for(a=a.parentNode;\"SPAN\"!==a.tagName.toUpperCase()&&\"text\"!==a.className.toLowerCase;)a=a.parentNode;APURI.pjono[APURI.count]=a;a.style.display=\"none\";var b=a.parentNode,c=a.parentNode.parentNode.querySelector(\"textarea.answerText\");c.id=\"apuri_vastk_\"+APURI.count;c.style.height=\"10px\";c.style.display=\"none\";c=APURI.purku(a);b.insertBefore(c,a.nextSibling)})();</script>"